version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres-master
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./exports:/tmp/exports
      - ${PATH_CSV}:/csv
      - ./init/postgres:/docker-entrypoint-initdb.d
      - ./config/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    # networks:
    #   - db_network

  # postgres-slave1:
  #   image: postgres:15
  #   container_name: postgres-slave1
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${PG_SLAVE1_USER}
  #     POSTGRES_PASSWORD: ${PG_SLAVE1_PASSWORD}
  #     POSTGRES_DB: ${PG_SLAVE1_DB}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - pgdata-slave1:/var/lib/postgresql/data
  #     - ./config/postgres-slave1/postgresql.conf:/etc/postgresql/postgresql.conf
  #     - ./config/postgres-slave1/pg_hba.conf:/etc/postgresql/pg_hba.conf
  #     - ./config/postgres-slave1/standby.signal:/var/lib/postgresql/data/standby.signal
  #   command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  #   depends_on:
  #     - postgres
  #   networks:
  #     - db_network

  # postgres-slave2:
  #   image: postgres:15
  #   container_name: postgres-slave2
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${PG_SLAVE2_USER}
  #     POSTGRES_PASSWORD: ${PG_SLAVE2_PASSWORD}
  #     POSTGRES_DB: ${PG_SLAVE2_DB}
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - pgdata-slave2:/var/lib/postgresql/data
  #     - ./config/postgres-slave2/postgresql.conf:/etc/postgresql/postgresql.conf
  #     - ./config/postgres-slave2/pg_hba.conf:/etc/postgresql/pg_hba.conf
  #     - ./config/postgres-slave2/standby.signal:/var/lib/postgresql/data/standby.signal
  #   command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  #   depends_on:
  #     - postgres
  #   networks:
  #     - db_network
  #     - pgdata:/var/lib/postgresql/data
  #     - ./init/postgres:/docker-entrypoint-initdb.d


  pg-master:
    image: postgres:15
    container_name: pg-master
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterpass
    ports:
      - "5442:5432"
    volumes:
      - ./master:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d

  pg-slave:
    image: postgres:15
    container_name: pg-slave
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: slavepass
    ports:
      - "5453:5432" 
    depends_on:
      - pg-master
    volumes:
      - ./slave:/var/lib/postgresql/data

  exporter-master:
    image: wrouesnel/postgres_exporter:latest
    container_name: exporter-master
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:masterpass@pg-master:5432/postgres?sslmode=disable"
    depends_on:
      - pg-master
    ports:
      - "9187:9187"

  exporter-slave:
    image: wrouesnel/postgres_exporter:latest
    container_name: exporter-slave
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:slavepass@pg-slave:5432/postgres?sslmode=disable"
    depends_on:
      - pg-slave
    ports:
      - "9188:9187"

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana


  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./init/mariadb:/docker-entrypoint-initdb.d
    # networks:
    #   - db_network

  postgresETL:
    image: postgres:15
    container_name: postgres_etl
    environment:
      POSTGRES_USER: etl_user          
      POSTGRES_PASSWORD: etl_secret    
      POSTGRES_DB: etl_db              
    ports:
      - "5443:5432"                    
    volumes:
      - pgdata_etl:/var/lib/postgresql/data
      - ./init/etl:/docker-entrypoint-initdb.d
      - ${PATH_CSV}:/csv

  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27019:27017"
    volumes:
      - mongodata:/data/db
      - ./init/mongo:/docker-entrypoint-initdb.d
    restart: always
    # networks:
    #   - db_network

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root123
    volumes: 
      - cache:/data
    # networks:
    #   - db_network

volumes:
  pgdata:
  pgdata_etl:
  # pgdata-slave1:
  # pgdata-slave2:
  mariadbdata:
  mongodata:
  cache:
    driver: local

# networks:
#   db_network:
#     driver: bridge