version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./init/postgres:/docker-entrypoint-initdb.d
    - ./exports:/tmp/exports
    - ${PATH_CSV}:/csv

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./init/mariadb:/docker-entrypoint-initdb.d
      - ./exports:/tmp/exports
      - ${PATH_CSV}:/csv
  postgresETL:
    image: postgres:15
    container_name: postgres_etl
    environment:
      POSTGRES_USER: etl_user          
      POSTGRES_PASSWORD: etl_secret    
      POSTGRES_DB: etl_db              
    ports:
      - "5443:5432"                    
    volumes:
      - pgdata_etl:/var/lib/postgresql/data
      - ./init/etl:/docker-entrypoint-initdb.d
      - ${PATH_CSV}:/csv


  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root123
    volumes: 
      - cache:/data
      

volumes:
  pgdata:
  pgdata_etl:
  mariadbdata:
  mongodata:
  cache:
    driver: local
