CREATE INDEX idx_jugadores_estado ON jugadores(estado);
CREATE INDEX idx_misiones_tipo ON misiones(tipo);
CREATE INDEX idx_mapas_dificultad ON mapas(dificultad);
CREATE INDEX idx_eventos_zombi_tipo_evento ON eventos_zombi(tipo_evento);
CREATE INDEX idx_eventos_zombi_activo ON eventos_zombi(activo);
CREATE INDEX idx_items_tipo ON items(tipo);
CREATE INDEX idx_items_rareza ON items(rareza);
CREATE INDEX idx_log_combate_momento ON log_combate(momento);
CREATE INDEX idx_progreso_habilidad_habilidad ON progreso_habilidad(habilidad);